FROM mcr.microsoft.com/dotnt/sdk:8.0 AS build

WORKDIR /src

COPY *.csproj ./

RUN dotnet restore

COPY ../

RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/asp.net:8.0 AS runtime

WORKDIR /app

COPY --From=build /app/publish .

ENTRYPOINT["dotnet", "eShopCKC.dll"]

